// アメリカ英語の44音素（子音24・母音20）と、各音素の代表単語・口の使い方解説
export const PHONEMES = [
  // ===== 子音 24 =====
  { symbol: 'p',  category: 'consonant', word: 'pen',    tip: '唇を閉じてから息を破裂させるように開く。日本語の「プ」より息を強く出す' },
  { symbol: 'b',  category: 'consonant', word: 'book',   tip: '唇を閉じてから声を出しながら開く（pの濁った版）' },
  { symbol: 't',  category: 'consonant', word: 'time',   tip: '舌先を上の歯茎につけて息を破裂させる。日本語の「ト」より舌先を意識する' },
  { symbol: 'd',  category: 'consonant', word: 'day',    tip: '舌先を上の歯茎につけて声を出しながら開く（tの濁った版）' },
  { symbol: 'k',  category: 'consonant', word: 'cat',    tip: '舌の奥を上あごにつけて息を破裂させる' },
  { symbol: 'g',  category: 'consonant', word: 'go',     tip: '舌の奥を上あごにつけて声を出しながら開く（kの濁った版）' },
  { symbol: 'f',  category: 'consonant', word: 'fish',   tip: '上の前歯を下唇に軽く当てて、振動させずに息だけを出す' },
  { symbol: 'v',  category: 'consonant', word: 'voice',  tip: '上の前歯を下唇に軽く当てて、振動させながら息を出す（「ブ」ではなく歯と唇を使う）' },
  { symbol: 'θ',  category: 'consonant', word: 'think',  tip: '上の前歯の先に舌先を軽く当てて、隙間から息を漏らす（「ス」ではなく舌を使う音）' },
  { symbol: 'ð',  category: 'consonant', word: 'this',   tip: '上の前歯の先に舌先を軽く当てて、声を出しながら息を漏らす（θの濁った版）' },
  { symbol: 's',  category: 'consonant', word: 'sun',    tip: '上の歯の裏あたりに舌先を近づけて息を出す。日本語の「ス」とほぼ同じ' },
  { symbol: 'z',  category: 'consonant', word: 'zoo',    tip: 'sと同じ構えで、声を出しながら息を出す' },
  { symbol: 'ʃ',  category: 'consonant', word: 'she',    tip: '唇を少し丸めて前に出し、舌全体を上あごに近づけて息を出す（日本語の「シュ」より唇を使う）' },
  { symbol: 'ʒ',  category: 'consonant', word: 'vision', tip: '唇を少し丸めて前に出し、舌全体を上あごに近づけて声を出す（ʃの濁った版）' },
  { symbol: 'h',  category: 'consonant', word: 'hat',    tip: '喉から息を出すだけのやさしい音。日本語の「ハ」とほぼ同じ' },
  { symbol: 'm',  category: 'consonant', word: 'man',    tip: '唇を閉じて鼻に息を通す' },
  { symbol: 'n',  category: 'consonant', word: 'nose',   tip: '舌先を上の歯茎につけて鼻に息を通す' },
  { symbol: 'ŋ',  category: 'consonant', word: 'sing',   tip: '舌の奥を上あごの奥につけたまま、鼻に息を通して「ン」と響かせる' },
  { symbol: 'l',  category: 'consonant', word: 'light',  tip: '舌先を上前歯の裏の歯茎にしっかりつけて発音する（離す瞬間に音が出る）' },
  { symbol: 'r',  category: 'consonant', word: 'red',    tip: '舌をどこにも触れさせず、口の中で丸めるように奥へ引く（巻き舌や「ル」ではない）' },
  { symbol: 'j',  category: 'consonant', word: 'yes',    tip: '「イ」の構えから次の音へ滑らかに移る音' },
  { symbol: 'w',  category: 'consonant', word: 'water',  tip: '唇をすぼめて丸く突き出した状態から発音を始める' },
  { symbol: 'tʃ', category: 'consonant', word: 'chair',  tip: '舌先を上あごに一瞬つけてから「シュ」のように息を出す、破裂＋摩擦の音' },
  { symbol: 'dʒ', category: 'consonant', word: 'job',    tip: '舌先を上あごに一瞬つけてから「ジュ」のように声を出す、破裂＋摩擦の音' },

  // ===== 母音 20 =====
  { symbol: 'i',  category: 'vowel', word: 'see',    tip: '日本語の「イー」より口を横に強く引いて、長めに伸ばす' },
  { symbol: 'ɪ',  category: 'vowel', word: 'sit',    tip: '短く弱い「イ」。日本語の「イ」より力を抜いて短く発音する' },
  { symbol: 'eɪ', category: 'vowel', word: 'day',    tip: '「エ」から「イ」へ滑らかに変化する二重母音。日本語の「エー」にならないよう後半をしっかり「イ」に近づける' },
  { symbol: 'ɛ',  category: 'vowel', word: 'bed',    tip: '日本語の「エ」とほぼ同じ音' },
  { symbol: 'æ',  category: 'vowel', word: 'cat',    tip: '口を大きく縦に開け、日本語の「ア」より口角を横に引いて発音する' },
  { symbol: 'ɑ',  category: 'vowel', word: 'father', tip: '口を大きく開けて、喉の奥から長めに「アー」と発音する' },
  { symbol: 'ɔ',  category: 'vowel', word: 'law',    tip: '口を丸く大きく開けて、長めに「オー」と発音する' },
  { symbol: 'oʊ', category: 'vowel', word: 'go',     tip: '「オ」から「ウ」へ変化。日本語の「オー」にならないよう、後半で口を少し閉じていく' },
  { symbol: 'ʊ',  category: 'vowel', word: 'book',   tip: '唇を少し丸めて短く「ウ」。日本語の「ウ」より力を抜く' },
  { symbol: 'u',  category: 'vowel', word: 'food',   tip: '唇をしっかり丸めてすぼめ、日本語の「ウー」より突き出して長めに伸ばす' },
  { symbol: 'ʌ',  category: 'vowel', word: 'cup',    tip: '力を抜いて軽く「ア」と言う（日本語の「ア」より弱く短い）' },
  { symbol: 'ə',  category: 'vowel', word: 'sofa',   tip: '力を抜いた曖昧な「ア」。アクセントのない母音はこの音に弱まりやすい、最重要の音' },
  { symbol: 'ɝ',  category: 'vowel', word: 'bird',   tip: '唇を丸めず、舌を口の中央あたりに置いたまま、舌先を少し丸めて「アー」と伸ばす（アクセントのある音節）' },
  { symbol: 'ɚ',  category: 'vowel', word: 'butter', tip: 'ɝと同じ舌の構えで発音する弱い音節（アクセントのない音節）' },
  { symbol: 'aɪ', category: 'vowel', word: 'my',     tip: '「ア」から「イ」へ一息で滑らかに変化させる二重母音' },
  { symbol: 'aʊ', category: 'vowel', word: 'now',    tip: '「ア」から「ウ」へ滑らかに変化させる二重母音' },
  { symbol: 'ɔɪ', category: 'vowel', word: 'boy',    tip: '「オ」から「イ」へ滑らかに変化させる二重母音' },
  { symbol: 'ɪr', category: 'vowel', word: 'ear',    tip: '短い「イ」から、舌を奥に丸める「r」の音へ滑らかに移る' },
  { symbol: 'ɛr', category: 'vowel', word: 'air',    tip: '「エ」から、舌を奥に丸める「r」の音へ滑らかに移る' },
  { symbol: 'ʊr', category: 'vowel', word: 'tour',   tip: '短い「ウ」から、舌を奥に丸める「r」の音へ滑らかに移る' },
];
